### ISSUE TITLE
Login Supabase

### ISSUE THREAD

**Issue by emibloque** [viccalvarezz/designme#1]
Después de [mirar la documentación](https://supabase.com/docs/reference/javascript/auth-signup), el `redirectTo` tiene que ser absoluto incluyendo puerto y protocolo, por lo que el fichero `AuthGitHubButton.tsx` se podría simplificar así:

```diff
 import { Button, ButtonProps } from "@chakra-ui/react";
-import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
-import { useRouter } from "next/router";
+import { useSupabaseClient } from "@supabase/auth-helpers-react";
 
 export const AuthGitHubButton = (props: ButtonProps) => {
   const supabaseClient = useSupabaseClient();
-  const session = useSession();
-  const router = useRouter();
 
   const handleClick = async () => {
-    if (session) {
-      router.push("/home");
-      return;
-    }
-
-    const { data, error } = await supabaseClient.auth.signInWithOAuth({
+    await supabaseClient.auth.signInWithOAuth({
       provider: "github",
       options: {
-        redirectTo: window.location.origin,
+        redirectTo: `${window.location.protocol}//${window.location.host}/home`,
       },
     });
   };

```

**Comment by viccalvarezz** [comment]
He probado esta posible solución y al hacer el log in muestra correctamente /home pero no cargan las distintas sesiones, de forma que queda la página de la siguiente manera: 
<img width="897" alt="Screenshot 2023-02-27 at 18 30 31" src="https://user-images.githubusercontent.com/43728577/221638686-c17c5d59-6bee-45e7-a492-127fad98fba2.png">
Ahora bien, si hago un refresh de la página si se ve correctamente.

**Comment by emibloque** [comment]
Puede ser que dentro de `home.tsx` en `getServerSideProps` no esté cogiendo la sesión bien?

**Comment by viccalvarezz** [comment]
Es un problema con Supabase y se puede encontrar los comentarios de la comunidad en https://github.com/orgs/supabase/discussions/12945.

Es por ello por lo que se planteó una solución momentánea a este problema y está implementada en el archivo [AuthRedirect](https://github.com/viccalvarezz/designme/blob/main/src/components/Auth/AuthRedirect.tsx).
